spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Coolplast@123
    url: jdbc:mysql://localhost:3306/ihis
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    
  mail:
    host: smtp.gmail.com
    username: sujatarokade18@gmail.com
    password: Rajendra@123
    port: 587
    properties:
      mail:
        smtp:
          ssl:
            auth: true
          starttls:
            enable: true